/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'keke' at '16/05/02 14:49' with Gradle 2.13
 *
 * @author keke, @date 16/05/02 14:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
